# Blowfish theme for Hugo

name = "Blowfish"
license = "MIT"
licenselink = "https://github.com/nunocoracao/blowfish/blob/main/LICENSE"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

homepage = "https://github.com/nunocoracao/blowfish/"
demosite = "https://blowfish.page/"

tags = ["blog", "minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["syntax highlighting", "dark mode", "emoji", "firebase", "views"]

[author]
  name = "Nuno Coracao"
  homepage = "https://n9o.xyz/"

[original]
  author = "James Panther"
  homepage = "https://jamespanther.com/"
  repo = "https://github.com/jpanther/congo"
